name: monitoring
description: A new Flutter package project.
version: 0.0.1

publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_analytics: ^10.4.4
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
    
flutter:

